apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-usage-test
spec:
  stressors:
    - memory:
        workers: 2 # Número de trabalhadores que consumirão memória
  mode: one
  selector:
    namespaces:
      - { $app_namespace }
  stressngStressors: {}
  containerNames:
    - { $container_name }
  duration: "5m" # Duração do teste de consumo de memória